package model

import (
	"time"

	"github.com/spiringo/spiringo/internal/pkg/orm"
)

// 中文：Notification 定义当前包使用的数据结构或接口。
// English: Notification defines a data structure or interface used by this package.
// Notification is an inbox message generated by notification delivery.
type Notification struct {
	// 中文：orm.TenantBaseModel 嵌入复用该类型提供的能力。
	// English: orm.TenantBaseModel embeds reusable behavior from that type.
	orm.TenantBaseModel
	// 中文：Event 保存当前结构中的配置或数据值。
	// English: Event stores a configuration or data value for this struct.
	Event string `gorm:"size:128;index;not null" json:"event"`
	// 中文：Severity 保存当前结构中的配置或数据值。
	// English: Severity stores a configuration or data value for this struct.
	Severity string `gorm:"size:32;index;not null" json:"severity"`
	// 中文：RecipientID 保存当前结构中的配置或数据值。
	// English: RecipientID stores a configuration or data value for this struct.
	RecipientID string `gorm:"size:64;index" json:"recipient_id,omitempty"`
	// 中文：Subject 保存当前结构中的配置或数据值。
	// English: Subject stores a configuration or data value for this struct.
	Subject string `gorm:"size:256;not null" json:"subject"`
	// 中文：Content 保存当前结构中的配置或数据值。
	// English: Content stores a configuration or data value for this struct.
	Content string `gorm:"type:text" json:"content,omitempty"`
	// 中文：Payload 保存当前结构中的配置或数据值。
	// English: Payload stores a configuration or data value for this struct.
	Payload string `gorm:"type:text" json:"payload,omitempty"`
	// 中文：ReadAt 保存当前结构中的配置或数据值。
	// English: ReadAt stores a configuration or data value for this struct.
	ReadAt *time.Time `gorm:"index" json:"read_at,omitempty"`
}

// 中文：TableName 执行当前包中的对应流程。
// English: TableName executes the corresponding workflow in this package.
func (Notification) TableName() string { return "notification_messages" }
